// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // `ts-node prisma/seed.ts` directo no resuelve los imports con
    // extensión .js del cliente generado (../generated/prisma, NodeNext) —
    // se compila con tsc (nest build) y se corre el JS ya emitido.
    seed: 'npm run build && node dist/prisma/seed.js',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
